version: '3.8'

name: "loginet"

services:

  sql-server:    
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - 1440:1433
    networks:
      - loginet
    environment:
      SA_PASSWORD: "Strong_p@ssword12"   
      ACCEPT_EULA: "Y"
 
  loginet-api:
    container_name: loginet-api
    build:
      context: .
      dockerfile: "./Loginet.TestTask.Api/Dockerfile"
    depends_on:
      - sql-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - FROM_DOCKER=true
    ports:
      - 5001:80
    networks:
      - loginet

networks:
  loginet:
    driver: bridge